version: '3.8'

services:
  # Databases
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Storage
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MLflow Tracking Server
  mlflow:
    build:
      context: ./services/mlflow
      dockerfile: Dockerfile
    container_name: mlops-mlflow
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:mlflow123@postgres:5432/mlflow
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=s3://mlflow-artifacts/
      - AWS_ACCESS_KEY_ID=mlflow
      - AWS_SECRET_ACCESS_KEY=mlflow123
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_VERIFY_SSL=false
      - MLFLOW_S3_IGNORE_TLS=true
      - MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING=true
      - MLFLOW_SYSTEM_METRICS_SAMPLING_INTERVAL=10
      - MLFLOW_SYSTEM_METRICS_SAMPLES_BEFORE_LOGGING=1
    ports:
      - "5050:5000"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Healthcare AI Model Service
  healthcare-ai:
    build:
      context: ./models/healthcare-ai
      dockerfile: Dockerfile
    container_name: mlops-healthcare-ai
    ports:
      - "8080:8000"
    environment:
      - MODEL_NAME=healthcare-ai
      - MODEL_VERSION=3.0.0
      - ENVIRONMENT=production
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    depends_on:
      - mlflow
    volumes:
      - model_artifacts:/app/artifacts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  postgres_data:
  redis_data:
  minio_data:
  model_artifacts:

networks:
  default:
    name: mlops-network