apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: healthcare-ai-dev
type: Opaque
data:
  # echo -n 'mlflow' | base64
  username: bWxmbG93
  # echo -n 'mlflow123' | base64  
  password: bWxmbG93MTIz
  # echo -n 'mlflow_dev' | base64
  database: bWxmbG93X2Rldg==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: healthcare-ai-dev
data:
  POSTGRES_DB: mlflow_dev
  POSTGRES_USER: mlflow

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: healthcare-ai-dev
  labels:
    app: postgres
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - mlflow
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - mlflow
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: healthcare-ai-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: healthcare-ai-dev
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres