global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'ab-testing'
    static_configs:
      - targets: ['ab-testing:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'healthcare-ai'
    static_configs:
      - targets: ['healthcare-ai:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s