apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthcare-ai-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sushil-negi/mlops-project.git
    targetRevision: HEAD
    path: gitops/manifests/healthcare-ai-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: healthcare-ai-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3