apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthcare-ai-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sushil-negi/mlops-project.git
    targetRevision: HEAD
    path: gitops/manifests/healthcare-ai-production
  destination:
    server: https://kubernetes.default.svc
    namespace: healthcare-ai-prod
  syncPolicy:
    # Manual sync for production - requires approval
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
  revisionHistoryLimit: 10