apiVersion: v1
kind: ConfigMap
metadata:
  name: ab-testing-config
  namespace: healthcare-ai-production
data:
  REDIS_URL: "redis://redis:6379"
  PROMETHEUS_URL: "http://prometheus:9090"
  ALERTMANAGER_URL: "http://alertmanager:9093"
  ENVIRONMENT: "production"
  LOG_LEVEL: "WARNING"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab-testing
  namespace: healthcare-ai-production
  labels:
    app: ab-testing
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ab-testing
  template:
    metadata:
      labels:
        app: ab-testing
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ab-testing
            topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - production
      initContainers:
      - name: wait-for-redis
        image: redis:7-alpine
        command:
        - sh
        - -c
        - |
          until redis-cli -h redis ping; do
            echo "Waiting for Redis..."
            sleep 2
          done
      containers:
      - name: ab-testing
        image: ab-testing:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: ab-testing-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"

---
apiVersion: v1
kind: Service
metadata:
  name: ab-testing
  namespace: healthcare-ai-production
  labels:
    app: ab-testing
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: ab-testing

---
apiVersion: v1
kind: Service
metadata:
  name: ab-testing-external
  namespace: healthcare-ai-production
  labels:
    app: ab-testing
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31008
  selector:
    app: ab-testing